spring:
  application:
    name: product-ms

  datasource:
    url: jdbc:postgresql://localhost:5434/product_db
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog.yaml
    contexts: dev
    drop-first: false
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK

server:
  port: 8081
  servlet:
    context-path: /product-ms

jwt:
  accessToken:
    secret: "CHANGE_THIS_TO_A_VERY_LONG_RANDOM_SECRET_KEY_256_BITS_ACCESS"
