version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: product-db_postgres
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: